using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace FollowPeers.Models
{
    public class SampleData : DropCreateDatabaseIfModelChanges<FollowPeersDBEntities>
    {
        protected override void Seed(FollowPeersDBEntities context)
        {
            new List<Organization>
            {
                new Organization {Name = "Singapore Polytechnics"},
                new Organization {Name = "Nanyang Polytechnics"},
                new Organization {Name = "Ngee Ann Polytechnics"},
                new Organization {Name = "Temasak Polytechnics"},
                new Organization {Name = "Republic Polytechnics"},
                new Organization {Name = "COLUMBIA University"},
                new Organization {Name = "CORNELL University"},
                new Organization {Name = "DARTMOUTH College"},
                new Organization {Name = "DELFT University of Technology"},
                new Organization {Name = "DUKE University"},
                new Organization {Name = "École normale supérieure, PARIS"},
                new Organization {Name = "ÉCOLE POLYTECHNIQUE"},
                new Organization {Name = "École Polytechnique Fédérale de LAUSANNE"},
                new Organization {Name = "EMORY University"},
                new Organization {Name = "ETH Zurich (Swiss Federal Institute of Technology)"},
                new Organization {Name = "Freie Universität BERLIN"},
                new Organization {Name = "GEORGIA Institute of Technology"},
                new Organization {Name = "HARVARD University"},
                new Organization {Name = "HEIDELBERG University"},
                new Organization {Name = "HONG KONG University of Science and Technology"},
                new Organization {Name = "IMPERIAL College London"},
                new Organization {Name = "JOHNS HOPKINS University"},
                new Organization {Name = "KAIST – Korea Advanced Institute of Science"},
                new Organization {Name = "Katholieke Universiteit LEUVEN"},
                new Organization {Name = "KING'S College London"},
                new Organization {Name = "KYOTO University"},
                new Organization {Name = "LEIDEN University"},
                new Organization {Name = "LONDON School of Economics and Political Science"},
                new Organization {Name = "Ludwig-Maximilians-Universität München"},
                new Organization {Name = "LUND University"},
                new Organization {Name = "MASSACHUSETTS Institute of Technology (MIT)"},
                new Organization {Name = "MCGILL University"},
                new Organization {Name = "MONASH University"},
                new Organization {Name = "NAGOYA University"},
                new Organization {Name = "Nanyang Technological University (NTU)"},
                new Organization {Name = "National TAIWAN University"},
                new Organization {Name = "National University of Singapore (NUS)"},
                new Organization {Name = "NEW YORK University(NYU)"},
                new Organization {Name = "NORTHWESTERN University"},
                new Organization {Name = "OSAKA University"},
                new Organization {Name = "PEKING University"},
                new Organization {Name = "PRINCETON University"},
                new Organization {Name = "PURDUE University"},
                new Organization {Name = "SEOUL National University"},
                new Organization {Name = "STANFORD University"},
                new Organization {Name = "Technische Universitaet Muenchen (TUM)"},
                new Organization {Name = "The CHINESE University of Hong Kong"},
                new Organization {Name = "The University of AUCKLAND"},
                new Organization {Name = "TOHOKU University"},
                new Organization {Name = "TOKYO Institute of Technology"},
                new Organization {Name = "TRINITY College Dublin"},
                new Organization {Name = "TSINGHUA University"},
                new Organization {Name = "UCL (University College London)"},
                new Organization {Name = "University College DUBLIN"},
                new Organization {Name = "University of ADELAIDE"},
                new Organization {Name = "University of ALBERTA"},
                new Organization {Name = "University of AMSTERDAM"},
                new Organization {Name = "University of BIRMINGHAM"},
                new Organization {Name = "University of BRISTOL"},
                new Organization {Name = "University of BRITISH COLUMBIA"},
                new Organization {Name = "University of California, BERKELEY"},
                new Organization {Name = "University of CALIFORNIA, Los Angeles (UCLA)"},
                new Organization {Name = "University of CALIFORNIA, San Diego"},
                new Organization {Name = "University of CAMBRIDGE"},
                new Organization {Name = "University of CHICAGO"},
                new Organization {Name = "University of COPENHAGEN"},
                new Organization {Name = "University of EDINBURGH"},
                new Organization {Name = "University of GENEVA"},
                new Organization {Name = "University of GLASGOW"},
                new Organization {Name = "University of HONGKONG"},
                new Organization {Name = "University of ILLINOIS, Chicago (UIC)"},
                new Organization {Name = "University of LEEDS"},
                new Organization {Name = "University of MANCHESTER"},
                new Organization {Name = "University of MELBOURNE"},
                new Organization {Name = "University of MICHIGAN"},
                new Organization {Name = "University of NEWSOUTH WALES"},
                new Organization {Name = "University of NORTH CAROLINA, Chapel Hill"},
                new Organization {Name = "University of NOTTINGHAM"},
                new Organization {Name = "University of OXFORD"},
                new Organization {Name = "University of PENNSYLVANIA"},
                new Organization {Name = "University of QUEENSLAND"},
                new Organization {Name = "University of SHEFFIELD"},
                new Organization {Name = "University of SOUTHAMPTON"},
                new Organization {Name = "University of STANDREWS"},
                new Organization {Name = "University of SYDNEY"},
                new Organization {Name = "University of TEXAS at Austin"},
                new Organization {Name = "University of TOKYO"},
                new Organization {Name = "University of TORONTO"},
                new Organization {Name = "University of WARWICK"},
                new Organization {Name = "University of WASHINGTON"},
                new Organization {Name = "University of WESTERN AUSTRALIA"},
                new Organization {Name = "University of WISCONSIN-Madison"},
                new Organization {Name = "University of YORK"},
                new Organization {Name = "University of ZURICH"},
                new Organization {Name = "UPPSALA University"},
                new Organization {Name = "UTRECHT University"},
                new Organization {Name = "WASHINGTON University in St. Louis"},
                new Organization {Name = "YALE University"}
            }.ForEach(a => context.Organizations.Add(a));

            new List<Department>
            {
                new Department {Name = "Aeronautics & Astronautics"},
                new Department {Name = "Anthropology"},
                new Department {Name = "Applied Physics"},
                new Department {Name = "Art and Art History"},
                new Department {Name = "Biochemistry"},
                new Department {Name = "Bioengineering"},
                new Department {Name = "Biology"},
                new Department {Name = "Business Management"},
                new Department {Name = "Cardiothoracic Surgery"},
                new Department {Name = "Chemical and Systems Biology"},
                new Department {Name = "Chemical Engineering"},
                new Department {Name = "Chemistry"},
                new Department {Name = "Civil and Environmental Engineering"},
                new Department {Name = "Communication"},
                new Department {Name = "Comparative Literature"},
                new Department {Name = "Computer Science"},
                new Department {Name = "Drama"},
                new Department {Name = "East Asian Languages and Cultures"},
                new Department {Name = "Economics"},
                new Department {Name = "English"},
                new Department {Name = "Environmental Sciences"},
                new Department {Name = "French and Italian"},
                new Department {Name = "Geophysics"},
                new Department {Name = "History"},
                new Department {Name = "Law School"},
                new Department {Name = "Linguistics"},
                new Department {Name = "Management Sciences"},
                new Department {Name = "Material Sciences and Engineering"},
                new Department {Name = "Microbiology"},
                new Department {Name = "Music"},
                new Department {Name = "Neurology"},
                new Department {Name = "Ophthalmology"},
                new Department {Name = "Pathology"},
                new Department {Name = "Physics"},
                new Department {Name = "Philosophy"},
                new Department {Name = "Polotical Science"},
                new Department {Name = "Psychiatry"},
                new Department {Name = "Psychology"},
                new Department {Name = "Radiology"},
                new Department {Name = "Religious Studies"},
                new Department {Name = "Sociology"},
                new Department {Name = "Statistics"}
            }.ForEach(a => context.Departments.Add(a));


            new List<Country>
            {
                new Country {Name = "Afghanistan"},
                new Country {Name = "Albania"},
                new Country {Name = "Algeria"},
                new Country {Name = "American Samoa"},
                new Country {Name = "Andorra"},
                new Country {Name = "Angola"},
                new Country {Name = "Anguilla"},
                new Country {Name = "Antarctica"},
                new Country {Name = "Antigua and Barbuda"},
                new Country {Name = "Argentina"},
                new Country {Name = "Armenia"},
                new Country {Name = "Aruba"},
                new Country {Name = "Australia"},
                new Country {Name = "Austria"},
                new Country {Name = "Azerbaijan"},
                new Country {Name = "Bahamas"},
                new Country {Name = "Bahrain"},
                new Country {Name = "Bangladesh"},
                new Country {Name = "Barbados"},
                new Country {Name = "Belarus"},
                new Country {Name = "Belgium"},
                new Country {Name = "Belize"},
                new Country {Name = "Benin"},
                new Country {Name = "Bermuda"},
                new Country {Name = "Bhutan"},
                new Country {Name = "Bolivia"},
                new Country {Name = "Bosnia and Herzegovina"},
                new Country {Name = "Botswana"},
                new Country {Name = "Bouvet Island"},
                new Country {Name = "Brazil"},
                new Country {Name = "British Indian Ocean Territory"},
                new Country {Name = "Brunei"},
                new Country {Name = "Bulgaria"},
                new Country {Name = "Burkina Faso"},
                new Country {Name = "Burundi"},
                new Country {Name = "Cambodia"},
                new Country {Name = "Cameroon"},
                new Country {Name = "Canada"},
                new Country {Name = "Cape Verde"},
                new Country {Name = "Cayman Islands"},
                new Country {Name = "Central African Republic"},
                new Country {Name = "Chad"},
                new Country {Name = "Chile"},
                new Country {Name = "China"},
                new Country {Name = "Christmas Island"},
                new Country {Name = "Cocos (Keeling) Islands"},
                new Country {Name = "Colombia"},
                new Country {Name = "Comoros"},
                new Country {Name = "Congo"},
                new Country {Name = "Congo, The Democratic Republic of the"},
                new Country {Name = "Cook Islands"},
                new Country {Name = "Costa Rica"},
                new Country {Name = "Côte d’Ivoire"},
                new Country {Name = "Croatia"},
                new Country {Name = "Cuba"},
                new Country {Name = "Cyprus"},
                new Country {Name = "Czech Republic"},
                new Country {Name = "Denmark"},
                new Country {Name = "Djibouti"},
                new Country {Name = "Dominica"},
                new Country {Name = "Dominican Republic"},
                new Country {Name = "East Timor"},
                new Country {Name = "Ecuador"},
                new Country {Name = "Egypt"},
                new Country {Name = "El Salvador"},
                new Country {Name = "Equatorial Guinea"},
                new Country {Name = "Eritrea"},
                new Country {Name = "Estonia"},
                new Country {Name = "Ethiopia"},
                new Country {Name = "Falkland Islands"},
                new Country {Name = "Faroe Islands"},
                new Country {Name = "Fiji Islands"},
                new Country {Name = "Finland"},
                new Country {Name = "France"},
                new Country {Name = "French Guiana"},
                new Country {Name = "French Polynesia"},
                new Country {Name = "French Southern territories"},
                new Country {Name = "Gabon"},
                new Country {Name = "Gambia"},
                new Country {Name = "Georgia"},
                new Country {Name = "Germany"},
                new Country {Name = "Ghana"},
                new Country {Name = "Gibraltar"},
                new Country {Name = "Greece"},
                new Country {Name = "Greenland"},
                new Country {Name = "Grenada"},
                new Country {Name = "Guadeloupe"},
                new Country {Name = "Guam"},
                new Country {Name = "Guatemala"},
                new Country {Name = "Guinea"},
                new Country {Name = "Guinea-Bissau"},
                new Country {Name = "Guyana"},
                new Country {Name = "Haiti"},
                new Country {Name = "Heard Island and McDonald Islands"},
                new Country {Name = "Holy See (Vatican City State)"},
                new Country {Name = "Honduras"},
                new Country {Name = "Hong Kong"},
                new Country {Name = "Hungary"},
                new Country {Name = "Iceland"},
                new Country {Name = "India"},
                new Country {Name = "Indonesia"},
                new Country {Name = "Iran"},
                new Country {Name = "Iraq"},
                new Country {Name = "Ireland"},
                new Country {Name = "Israel"},
                new Country {Name = "Italy"},
                new Country {Name = "Jamaica"},
                new Country {Name = "Japan"},
                new Country {Name = "Jordan"},
                new Country {Name = "Kazakstan"},
                new Country {Name = "Kenya"},
                new Country {Name = "Kiribati"},
                new Country {Name = "Kuwait"},
                new Country {Name = "Kyrgyzstan"},
                new Country {Name = "Laos"},
                new Country {Name = "Latvia"},
                new Country {Name = "Lebanon"},
                new Country {Name = "Lesotho"},
                new Country {Name = "Liberia"},
                new Country {Name = "Libyan Arab Jamahiriya"},
                new Country {Name = "Liechtenstein"},
                new Country {Name = "Lithuania"},
                new Country {Name = "Luxembourg"},
                new Country {Name = "Macao"},
                new Country {Name = "Macedonia"},
                new Country {Name = "Madagascar"},
                new Country {Name = "Malawi"},
                new Country {Name = "Malaysia"},
                new Country {Name = "Maldives"},
                new Country {Name = "Mali"},
                new Country {Name = "Malta"},
                new Country {Name = "Marshall Islands"},
                new Country {Name = "Martinique"},
                new Country {Name = "Mauritania"},
                new Country {Name = "Mauritius"},
                new Country {Name = "Mayotte"},
                new Country {Name = "Mexico"},
                new Country {Name = "Micronesia, Federated States of"},
                new Country {Name = "Moldova"},
                new Country {Name = "Monaco"},
                new Country {Name = "Mongolia"},
                new Country {Name = "Montserrat"},
                new Country {Name = "Morocco"},
                new Country {Name = "Mozambique"},
                new Country {Name = "Myanmar"},
                new Country {Name = "Namibia"},
                new Country {Name = "Nauru"},
                new Country {Name = "Nepal"},
                new Country {Name = "Netherlands"},
                new Country {Name = "Netherlands Antilles"},
                new Country {Name = "New Caledonia"},
                new Country {Name = "New Zealand"},
                new Country {Name = "Nicaragua"},
                new Country {Name = "Niger"},
                new Country {Name = "Nigeria"},
                new Country {Name = "Niue"},
                new Country {Name = "Norfolk Island"},
                new Country {Name = "North Korea"},
                new Country {Name = "Northern Mariana Islands"},
                new Country {Name = "Norway"},
                new Country {Name = "Oman"},
                new Country {Name = "Pakistan"},
                new Country {Name = "Palau"},
                new Country {Name = "Palestine"},
                new Country {Name = "Panama"},
                new Country {Name = "Papua New Guinea"},
                new Country {Name = "Paraguay"},
                new Country {Name = "Peru"},
                new Country {Name = "Philippines"},
                new Country {Name = "Pitcairn"},
                new Country {Name = "Poland"},
                new Country {Name = "Portugal"},
                new Country {Name = "Puerto Rico"},
                new Country {Name = "Qatar"},
                new Country {Name = "Réunion"},
                new Country {Name = "Romania"},
                new Country {Name = "Russian Federation"},
                new Country {Name = "Rwanda"},
                new Country {Name = "Saint Helena"},
                new Country {Name = "Saint Kitts and Nevis"},
                new Country {Name = "Saint Lucia"},
                new Country {Name = "Saint Pierre and Miquelon"},
                new Country {Name = "Saint Vincent and the Grenadines"},
                new Country {Name = "Samoa"},
                new Country {Name = "San Marino"},
                new Country {Name = "Sao Tome and Principe"},
                new Country {Name = "Saudi Arabia"},
                new Country {Name = "Senegal"},
                new Country {Name = "Seychelles"},
                new Country {Name = "Sierra Leone"},
                new Country {Name = "Singapore"},
                new Country {Name = "Slovakia"},
                new Country {Name = "Slovenia"},
                new Country {Name = "Solomon Islands"},
                new Country {Name = "Somalia"},
                new Country {Name = "South Africa"},
                new Country {Name = "South Georgia and the South Sandwich Islands"},
                new Country {Name = "South Korea"},
                new Country {Name = "Spain"},
                new Country {Name = "Sri Lanka"},
                new Country {Name = "Sudan"},
                new Country {Name = "Suriname"},
                new Country {Name = "Svalbard and Jan Mayen"},
                new Country {Name = "Swaziland"},
                new Country {Name = "Sweden"},
                new Country {Name = "Switzerland"},
                new Country {Name = "Syria"},
                new Country {Name = "Taiwan"},
                new Country {Name = "Tajikistan"},
                new Country {Name = "Tanzania"},
                new Country {Name = "Thailand"},
                new Country {Name = "Togo"},
                new Country {Name = "Tokelau"},
                new Country {Name = "Tonga"},
                new Country {Name = "Trinidad and Tobago"},
                new Country {Name = "Tunisia"},
                new Country {Name = "Turkey"},
                new Country {Name = "Turkmenistan"},
                new Country {Name = "Turks and Caicos Islands"},
                new Country {Name = "Tuvalu"},
                new Country {Name = "Uganda"},
                new Country {Name = "Ukraine"},
                new Country {Name = "United Arab Emirates"},
                new Country {Name = "United Kingdom"},
                new Country {Name = "United States"},
                new Country {Name = "United States Minor Outlying Islands"},
                new Country {Name = "Uruguay"},
                new Country {Name = "Uzbekistan"},
                new Country {Name = "Vanuatu"},
                new Country {Name = "Venezuela"},
                new Country {Name = "Vietnam"},
                new Country {Name = "Virgin Islands, British"},
                new Country {Name = "Virgin Islands, U.S."},
                new Country {Name = "Wallis and Futuna"},
                new Country {Name = "Western Sahara"},
                new Country {Name = "Yemen"},
                new Country {Name = "Yugoslavia"},
                new Country {Name = "Zambia"},
                new Country {Name = "Zimbabwe"}
         
            }.ForEach(a => context.Countries.Add(a));

            new List<Specialization>
            {
                new Specialization {Field = "Agricultural Science",SpecializationName="Agricultural Economics"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Agricultural Engineering"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Agricultural Philosophy"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Agricultural Plant Science"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Agronomy"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Agrophysics"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Animal Science"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Aquaculture"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Biosystems Engineering"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Environmental Science"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Food Science"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Horticulture"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Irrigation and Water Management"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Plant Fertilization, Animal and Human Nutrition"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Plant Protection and Animal Health"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Soil Science"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Theoretical Production Ecology"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Waste Management"},
                new Specialization {Field = "Agricultural Science",SpecializationName="Water Science"},

                new Specialization {Field = "Anthropology",SpecializationName="Anthropological Linguistics"},
                new Specialization {Field = "Anthropology",SpecializationName="Archaeology"},
                new Specialization {Field = "Anthropology",SpecializationName="Biological Anthropology"},
                new Specialization {Field = "Anthropology",SpecializationName="Cultural Anthropology"},
                new Specialization {Field = "Anthropology",SpecializationName="Historical Anthropology"},
                new Specialization {Field = "Anthropology",SpecializationName="Medical Anthropology"},

                new Specialization {Field = "Biology",SpecializationName="Aerobiology"},
                new Specialization {Field = "Biology",SpecializationName="Anatomy"},
                new Specialization {Field = "Biology",SpecializationName="Animal Communications"},
                new Specialization {Field = "Biology",SpecializationName="Bioinformatics"},
                new Specialization {Field = "Biology",SpecializationName="Biostatics"},
                new Specialization {Field = "Biology",SpecializationName="Biotechnology"},
                new Specialization {Field = "Biology",SpecializationName="Botany"},
                new Specialization {Field = "Biology",SpecializationName="Cancer Research"},
                new Specialization {Field = "Biology",SpecializationName="Canopy Research"},
                new Specialization {Field = "Biology",SpecializationName="Cell Biology"},
                new Specialization {Field = "Biology",SpecializationName="Chronobiology"},
                new Specialization {Field = "Biology",SpecializationName="Cryobiology"},
                new Specialization {Field = "Biology",SpecializationName="Ecolgy"},
                new Specialization {Field = "Biology",SpecializationName="Endocrinology"},
                new Specialization {Field = "Biology",SpecializationName="Entomology"},
                new Specialization {Field = "Biology",SpecializationName="Ethnobotany"},
                new Specialization {Field = "Biology",SpecializationName="Evolutionary Biology"},
                new Specialization {Field = "Biology",SpecializationName="Genetics"},

                new Specialization {Field = "Chemistry",SpecializationName="Analytical Chemistry"},
                new Specialization {Field = "Chemistry",SpecializationName="Astrochemistry"},
                new Specialization {Field = "Chemistry",SpecializationName="Biochemistry"},
                new Specialization {Field = "Chemistry",SpecializationName="Chemical Engineering"},
                new Specialization {Field = "Chemistry",SpecializationName="Chemical Kinetics"},
                new Specialization {Field = "Chemistry",SpecializationName="Nuclear Chemistry"},

                new Specialization {Field = "Computer Science",SpecializationName="Algorithms"},
                new Specialization {Field = "Computer Science",SpecializationName="Artificial Intelligence"},
                new Specialization {Field = "Computer Science",SpecializationName="Computer Architecture"},
                new Specialization {Field = "Computer Science",SpecializationName="Computer Graphics"},
                new Specialization {Field = "Computer Science",SpecializationName="Operating Systems"},
                new Specialization {Field = "Computer Science",SpecializationName="Parallel Computing"},

                new Specialization {Field = "Design",SpecializationName="Communication Design"},
                new Specialization {Field = "Design",SpecializationName="Fashion Design"},
                new Specialization {Field = "Design",SpecializationName="Graphic Design"},
                new Specialization {Field = "Design",SpecializationName="Industrial Design"},

                new Specialization {Field = "Engineering",SpecializationName="Acoustic Engineering"},
                new Specialization {Field = "Engineering",SpecializationName="Aeronautical Engineering"},
                new Specialization {Field = "Engineering",SpecializationName="Aerospace Engineering"},
                new Specialization {Field = "Engineering",SpecializationName="Bioengineering"},
                new Specialization {Field = "Engineering",SpecializationName="Civil Engineering"},
                new Specialization {Field = "Engineering",SpecializationName="Electrical Engineering"},
                new Specialization {Field = "Engineering",SpecializationName="Industrial Engineering"},
                new Specialization {Field = "Engineering",SpecializationName="Mechanical Engineering"},

                new Specialization {Field = "Law",SpecializationName="Civil Law"},
                new Specialization {Field = "Law",SpecializationName="Criminal Law"},
                new Specialization {Field = "Law",SpecializationName="Public Law"},

                new Specialization {Field = "Mathematics",SpecializationName="Algebra"},
                new Specialization {Field = "Mathematics",SpecializationName="Analysis"},
                new Specialization {Field = "Mathematics",SpecializationName="Number Theory"},
                new Specialization {Field = "Mathematics",SpecializationName="Probability Theory"},

                new Specialization {Field = "Religious Studies",SpecializationName="Abrahamic Religions"},
                new Specialization {Field = "Religious Studies",SpecializationName="Atheism and Humanism"},
                new Specialization {Field = "Religious Studies",SpecializationName="Comparative Religion"},
                new Specialization {Field = "Religious Studies",SpecializationName="Mythology and Folklore"}
            }.ForEach(a => context.Specializations.Add(a));

            new List<Industry>
            {
                new Industry {Name="Agriculture"},
                new Industry {Name="Automotive Products & Services"},
                new Industry {Name="Aviation"},
                new Industry {Name="Biotechnology & Life Sciences"},
                new Industry {Name="Building Services & Products"},
                new Industry {Name="Education & Training"},
                new Industry {Name="Entertainment & Film"},
                new Industry {Name="Fashion & Beauty"},
                new Industry {Name="Financial, Business & Legal Services"},
                new Industry {Name="Food & Beverage"},
                new Industry {Name="Greentech, Environmental & Eco"},
                new Industry {Name="Hospitality, Restaurants & Bars"},
                new Industry {Name="Internet, eCommerce & Apps"},
                new Industry {Name="IT, Hardware & Software"},
                new Industry {Name="Leisure, Tourism & Hotels"},
                new Industry {Name="Manufacturing"},
                new Industry {Name="Marketing & Advertising"},
                new Industry {Name="Media & Publishing"},
                new Industry {Name="Medical, Pharmaceuticals & Health Care"},
                new Industry {Name="Mining, Oil & Gas"},
                new Industry {Name="Products & Inventions"},
                new Industry {Name="Real Estate"},
                new Industry {Name="Retail"},
                new Industry {Name="Security & Defence"},
                new Industry {Name="Technology"},
                new Industry {Name="Telecom & Mobile"},
                new Industry {Name="Transportation"}
            }.ForEach(a => context.Industries.Add(a));


            // Adding Forum Categories - Ritesh

            var list = new List<Forum>();
            new List<Forum>
            {
                new Forum {Field = "Agricultural Science",Category="Agricultural Economics", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Agricultural Engineering", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Agricultural Philosophy", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Agricultural Plant Science", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Agronomy", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Agrophysics", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Animal Science", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Aquaculture", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Biosystems Engineering", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Environmental Science", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Food Science", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Horticulture" , Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Irrigation and Water Management", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Plant Fertilization, Animal and Human Nutrition", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Plant Protection and Animal Health", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Soil Science", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Theoretical Production Ecology", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Waste Management", Topics = new List<ForumTopic>()},
                new Forum {Field = "Agricultural Science",Category="Water Science", Topics = new List<ForumTopic>()},

                new Forum {Field = "Anthropology",Category="Anthropological Linguistics", Topics = new List<ForumTopic>()},
                new Forum {Field = "Anthropology",Category="Archaeology", Topics = new List<ForumTopic>()},
                new Forum {Field = "Anthropology",Category="Biological Anthropology", Topics = new List<ForumTopic>()},
                new Forum {Field = "Anthropology",Category="Cultural Anthropology", Topics = new List<ForumTopic>()},
                new Forum {Field = "Anthropology",Category="Historical Anthropology", Topics = new List<ForumTopic>()},
                new Forum {Field = "Anthropology",Category="Medical Anthropology", Topics = new List<ForumTopic>()},

                new Forum {Field = "Biology",Category="Aerobiology", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Anatomy", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Animal Communications", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Bioinformatics", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Biostatics", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Biotechnology", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Botany", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Cancer Research", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Canopy Research", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Cell Biology", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Chronobiology", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Cryobiology", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Ecolgy", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Endocrinology", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Entomology", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Ethnobotany", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Evolutionary Biology", Topics = new List<ForumTopic>()},
                new Forum {Field = "Biology",Category="Genetics", Topics = new List<ForumTopic>()},

                new Forum {Field = "Chemistry",Category="Analytical Chemistry", Topics = new List<ForumTopic>()},
                new Forum {Field = "Chemistry",Category="Astrochemistry", Topics = new List<ForumTopic>()},
                new Forum {Field = "Chemistry",Category="Biochemistry", Topics = new List<ForumTopic>()},
                new Forum {Field = "Chemistry",Category="Chemical Engineering", Topics = new List<ForumTopic>()},
                new Forum {Field = "Chemistry",Category="Chemical Kinetics", Topics = new List<ForumTopic>()},
                new Forum {Field = "Chemistry",Category="Nuclear Chemistry", Topics = new List<ForumTopic>()},

                new Forum {Field = "Computer Science",Category="Algorithms", Topics = new List<ForumTopic>()},
                new Forum {Field = "Computer Science",Category="Artificial Intelligence", Topics = new List<ForumTopic>()},
                new Forum {Field = "Computer Science",Category="Computer Architecture", Topics = new List<ForumTopic>()},
                new Forum {Field = "Computer Science",Category="Computer Graphics", Topics = new List<ForumTopic>()},
                new Forum {Field = "Computer Science",Category="Operating Systems", Topics = new List<ForumTopic>()},
                new Forum {Field = "Computer Science",Category="Parallel Computing", Topics = new List<ForumTopic>()},

                new Forum {Field = "Design",Category="Communication Design", Topics = new List<ForumTopic>()},
                new Forum {Field = "Design",Category="Fashion Design", Topics = new List<ForumTopic>()},
                new Forum {Field = "Design",Category="Graphic Design", Topics = new List<ForumTopic>()},
                new Forum {Field = "Design",Category="Industrial Design", Topics = new List<ForumTopic>()},

                new Forum {Field = "Engineering",Category="Acoustic Engineering", Topics = new List<ForumTopic>()},
                new Forum {Field = "Engineering",Category="Aeronautical Engineering", Topics = new List<ForumTopic>()},
                new Forum {Field = "Engineering",Category="Aerospace Engineering", Topics = new List<ForumTopic>()},
                new Forum {Field = "Engineering",Category="Bioengineering", Topics = new List<ForumTopic>()},
                new Forum {Field = "Engineering",Category="Civil Engineering", Topics = new List<ForumTopic>()},
                new Forum {Field = "Engineering",Category="Electrical Engineering", Topics = new List<ForumTopic>()},
                new Forum {Field = "Engineering",Category="Industrial Engineering", Topics = new List<ForumTopic>()},
                new Forum {Field = "Engineering",Category="Mechanical Engineering", Topics = new List<ForumTopic>()},

                new Forum {Field = "Law",Category="Civil Law", Topics = new List<ForumTopic>()},
                new Forum {Field = "Law",Category="Criminal Law", Topics = new List<ForumTopic>()},
                new Forum {Field = "Law",Category="Public Law", Topics = new List<ForumTopic>()},

                new Forum {Field = "Mathematics",Category="Algebra", Topics = new List<ForumTopic>()},
                new Forum {Field = "Mathematics",Category="Analysis", Topics = new List<ForumTopic>()},
                new Forum {Field = "Mathematics",Category="Number Theory", Topics = new List<ForumTopic>()},
                new Forum {Field = "Mathematics",Category="Probability Theory", Topics = new List<ForumTopic>()},

                new Forum {Field = "Religious Studies",Category="Abrahamic Religions", Topics = new List<ForumTopic>()},
                new Forum {Field = "Religious Studies",Category="Atheism and Humanism", Topics = new List<ForumTopic>()},
                new Forum {Field = "Religious Studies",Category="Comparative Religion", Topics = new List<ForumTopic>()},
                new Forum {Field = "Religious Studies",Category="Mythology and Folklore", Topics = new List<ForumTopic>() }

            }.ForEach(a => list.Add(a));
            
            list.ForEach(a => a.Topics.Add(new ForumTopic { Name = "General FAQs & Forum Rules", Description = "Find & post answers to FAQs & rules here", Category = a.Category }));
            list.ForEach(a => context.Forums.Add(a));

            new List<University>
            {
                new University {Name = "Singapore Polytechnics"},
                new University {Name = "Nanyang Polytechnics"},
                new University {Name = "Ngee Ann Polytechnics"},
                new University {Name = "Temasak Polytechnics"},
                new University {Name = "Republic Polytechnics"},
                new University {Name = "COLUMBIA University"},
                new University {Name = "CORNELL University"},
                new University {Name = "DARTMOUTH College"},
                new University {Name = "DELFT University of Technology"},
                new University {Name = "DUKE University"},
                new University {Name = "École normale supérieure, PARIS"},
                new University {Name = "ÉCOLE POLYTECHNIQUE"},
                new University {Name = "École Polytechnique Fédérale de LAUSANNE"},
                new University {Name = "EMORY University"},
                new University {Name = "ETH Zurich (Swiss Federal Institute of Technology)"},
                new University {Name = "Freie Universität BERLIN"},
                new University {Name = "GEORGIA Institute of Technology"},
                new University {Name = "HARVARD University"},
                new University {Name = "HEIDELBERG University"},
                new University {Name = "HONG KONG University of Science and Technology"},
                new University {Name = "IMPERIAL College London"},
                new University {Name = "JOHNS HOPKINS University"},
                new University {Name = "KAIST – Korea Advanced Institute of Science"},
                new University {Name = "Katholieke Universiteit LEUVEN"},
                new University {Name = "KING'S College London"},
                new University {Name = "KYOTO University"},
                new University {Name = "LEIDEN University"},
                new University {Name = "LONDON School of Economics and Political Science"},
                new University {Name = "Ludwig-Maximilians-Universität München"},
                new University {Name = "LUND University"},
                new University {Name = "MASSACHUSETTS Institute of Technology (MIT)"},
                new University {Name = "MCGILL University"},
                new University {Name = "MONASH University"},
                new University {Name = "NAGOYA University"},
                new University {Name = "Nanyang Technological University (NTU)"},
                new University {Name = "National TAIWAN University"},
                new University {Name = "National University of Singapore (NUS)"},
                new University {Name = "NEW YORK University(NYU)"},
                new University {Name = "NORTHWESTERN University"},
                new University {Name = "OSAKA University"},
                new University {Name = "PEKING University"},
                new University {Name = "PRINCETON University"},
                new University {Name = "PURDUE University"},
                new University {Name = "SEOUL National University"},
                new University {Name = "STANFORD University"},
                new University {Name = "Technische Universitaet Muenchen (TUM)"},
                new University {Name = "The CHINESE University of Hong Kong"},
                new University {Name = "The University of AUCKLAND"},
                new University {Name = "TOHOKU University"},
                new University {Name = "TOKYO Institute of Technology"},
                new University {Name = "TRINITY College Dublin"},
                new University {Name = "TSINGHUA University"},
                new University {Name = "UCL (University College London)"},
                new University {Name = "University College DUBLIN"},
                new University {Name = "University of ADELAIDE"},
                new University {Name = "University of ALBERTA"},
                new University {Name = "University of AMSTERDAM"},
                new University {Name = "University of BIRMINGHAM"},
                new University {Name = "University of BRISTOL"},
                new University {Name = "University of BRITISH COLUMBIA"},
                new University {Name = "University of California, BERKELEY"},
                new University {Name = "University of CALIFORNIA, Los Angeles (UCLA)"},
                new University {Name = "University of CALIFORNIA, San Diego"},
                new University {Name = "University of CAMBRIDGE"},
                new University {Name = "University of CHICAGO"},
                new University {Name = "University of COPENHAGEN"},
                new University {Name = "University of EDINBURGH"},
                new University {Name = "University of GENEVA"},
                new University {Name = "University of GLASGOW"},
                new University {Name = "University of HONGKONG"},
                new University {Name = "University of ILLINOIS, Chicago (UIC)"},
                new University {Name = "University of LEEDS"},
                new University {Name = "University of MANCHESTER"},
                new University {Name = "University of MELBOURNE"},
                new University {Name = "University of MICHIGAN"},
                new University {Name = "University of NEWSOUTH WALES"},
                new University {Name = "University of NORTH CAROLINA, Chapel Hill"},
                new University {Name = "University of NOTTINGHAM"},
                new University {Name = "University of OXFORD"},
                new University {Name = "University of PENNSYLVANIA"},
                new University {Name = "University of QUEENSLAND"},
                new University {Name = "University of SHEFFIELD"},
                new University {Name = "University of SOUTHAMPTON"},
                new University {Name = "University of STANDREWS"},
                new University {Name = "University of SYDNEY"},
                new University {Name = "University of TEXAS at Austin"},
                new University {Name = "University of TOKYO"},
                new University {Name = "University of TORONTO"},
                new University {Name = "University of WARWICK"},
                new University {Name = "University of WASHINGTON"},
                new University {Name = "University of WESTERN AUSTRALIA"},
                new University {Name = "University of WISCONSIN-Madison"},
                new University {Name = "University of YORK"},
                new University {Name = "University of ZURICH"},
                new University {Name = "UPPSALA University"},
                new University {Name = "UTRECHT University"},
                new University {Name = "WASHINGTON University in St. Louis"},
                new University {Name = "YALE University"}
            }.ForEach(a => context.Universities.Add(a));

            new List<Journal>
            {
                new Journal {Name = "Advanced Packaging, IEEE Transactions on"},
                new Journal {Name = "Aerospace and Electronic Systems, IEEE Transactions on"},
                new Journal {Name = "Communications Letters, IEEE"},
                new Journal {Name = "Display Technology, Journal of"},
                new Journal {Name = "Image Processing, IEEE Transactions on"},
                new Journal {Name = "Magnetics, IEEE Transactions on"},
                new Journal {Name = "Power Delivery, IEEE Transactions on"},
                new Journal {Name = "Quantum Electronics, IEEE Journal of"},
                new Journal {Name = "Sensors Journal, IEEE"},
                new Journal {Name = "Signal Processing Letters, IEEE"},
            }.ForEach(a => context.Journals.Add(a));

            new List<Publisher>
            {
                new Publisher {Name = "American Medical Association"},
                new Publisher {Name = "Annual Reviews"},
                new Publisher {Name = "Elsevier periodicals"},
                new Publisher {Name = "Geoscience"},
                new Publisher {Name = "Institute of Electrical and Electronics Engineers publications"},
                new Publisher {Name = "Johns Hopkins University Press"},
                new Publisher {Name = "MIT Press"},
                new Publisher {Name = "University of California Press"},
                new Publisher {Name = "University of Chicago Press"},
                new Publisher {Name = "University of Texas Press"},
            }.ForEach(a => context.Publishers.Add(a));

            new List<Conference>
            {
                new Conference {Name = "STOC - ACM"},
                new Conference {Name = "FOCS - IEEE"},
                new Conference {Name = "ICALP"},
                new Conference {Name = "STACS"},
                new Conference {Name = "ISAAC"},
                new Conference {Name = "MFCS"},
                new Conference {Name = "FSTTCS - IARCS"},
                new Conference {Name = "COCOON"},
                new Conference {Name = "WoLLIC"},
                new Conference {Name = "SODA - ACM–SIAM"},
                new Conference {Name = "ESA"},
                new Conference {Name = "WADS"},
                new Conference {Name = "SWAT"},
                new Conference {Name = "WAOA"},
                new Conference {Name = "SoCG - ACM"},
                new Conference {Name = "GD"},
                new Conference {Name = "IMR"},
                new Conference {Name = "WAFR"},
                new Conference {Name = "CCCG"},
                new Conference {Name = "EuroCG"},
                new Conference {Name = "LICS - IEEE "},
                new Conference {Name = "DLT"},
                new Conference {Name = "CIAA"},
            }.ForEach(a => context.Conferences.Add(a));
        }
    }
}
